### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by leocmarques** [thangqd/HCMGIS#12]
Hello, I am having a little QGIS course and many of my students got this error message:

Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method

locale.Error: unsupported locale setting
Traceback (most recent call last):
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
plugins[packageName] = package.classFactory(iface)
File "C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\__init__.py", line 11, in classFactory
from .hcmgis_menu import hcmgis_menu
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_menu.py", line 11, in
from .hcmgis_dialogs import *
File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
mod = _builtin_import(name, globals, locals, fromlist, level)
File "C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 908, in
class hcmgis_microsoft_dialog(hcmgis_dialog, Ui_hcmgis_microsoft_form):
File "C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 928, in hcmgis_microsoft_dialog
locale.setlocale(locale.LC_ALL, 'en_US')
File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\locale.py", line 604, in setlocale
return _setlocale(category, locale)
locale.Error: unsupported locale setting

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Versão do QGIS: 3.10.9-A Coruña A Coruña, bf47e9d3e1

Caminho do Python:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Obeng10/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Obeng10\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms

**Comment by hery84** [comment]
same Here...

Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method 

locale.Error: unsupported locale setting 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/overkill/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/__init__.py", line 11, in classFactory
    from .hcmgis_menu import hcmgis_menu
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/overkill/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_menu.py", line 11, in 
    from .hcmgis_dialogs import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/overkill/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 908, in 
    class hcmgis_microsoft_dialog(hcmgis_dialog, Ui_hcmgis_microsoft_form):
  File "/home/overkill/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 928, in hcmgis_microsoft_dialog
    locale.setlocale(locale.LC_ALL, 'en_US')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting


Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8

**Comment by thangqd** [comment]
Please try the latest version (21.1.29) @leocmarques, @hery84

**Comment by canunen** [comment]
Hi, I'm getting a similar dialogue with a different error: 

Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'certifi' 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/__init__.py", line 11, in classFactory
    from .hcmgis_menu import hcmgis_menu
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_menu.py", line 11, in 
    from .hcmgis_dialogs import *
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 22, in 
    from owslib.wfs import WebFeatureService
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/owslib/wfs.py", line 16, in 
    from .feature import wfs100, wfs110, wfs200
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/owslib/feature/wfs100.py", line 33, in 
    import pyproj
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/pyproj/__init__.py", line 49, in 
    import pyproj.network
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.9/site-packages/pyproj/network.py", line 8, in 
    import certifi
  File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'certifi'


Python version: 3.9.5 (default, May  9 2021, 14:00:28) [GCC 10.2.0] 
QGIS version: 3.18.2-Zürich Zürich, exported 

Python Path:
/usr/share/qgis/python
/home/can/.local/share/QGIS/QGIS3/profiles/default/python
/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/can/.local/lib/python3.9/site-packages
/usr/lib/python3.9/site-packages
/home/can/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by thangqd** [comment]
> Hi, I'm getting a similar dialogue with a different error:
> 
> Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method
> 
> ModuleNotFoundError: No module named 'certifi'
> Traceback (most recent call last):
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 335, in _startPlugin
> plugins[packageName] = package.classFactory(iface)
> File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/**init**.py", line 11, in classFactory
> from .hcmgis_menu import hcmgis_menu
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_menu.py", line 11, in
> from .hcmgis_dialogs import *
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 22, in
> from owslib.wfs import WebFeatureService
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/owslib/wfs.py", line 16, in
> from .feature import wfs100, wfs110, wfs200
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/owslib/feature/wfs100.py", line 33, in
> import pyproj
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/pyproj/**init**.py", line 49, in
> import pyproj.network
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/pyproj/network.py", line 8, in
> import certifi
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'certifi'
> 
> Python version: 3.9.5 (default, May 9 2021, 14:00:28) [GCC 10.2.0]
> QGIS version: 3.18.2-Zürich Zürich, exported
> 
> Python Path:
> /usr/share/qgis/python
> /home/can/.local/share/QGIS/QGIS3/profiles/default/python
> /home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python39.zip
> /usr/lib/python3.9
> /usr/lib/python3.9/lib-dynload
> /home/can/.local/lib/python3.9/site-packages
> /usr/lib/python3.9/site-packages
> /home/can/.local/share/QGIS/QGIS3/profiles/default/

**Comment by thangqd** [comment]
> Hi, I'm getting a similar dialogue with a different error:
> 
> Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method
> 
> ModuleNotFoundError: No module named 'certifi'
> Traceback (most recent call last):
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 335, in _startPlugin
> plugins[packageName] = package.classFactory(iface)
> File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/**init**.py", line 11, in classFactory
> from .hcmgis_menu import hcmgis_menu
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_menu.py", line 11, in
> from .hcmgis_dialogs import *
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 22, in
> from owslib.wfs import WebFeatureService
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/owslib/wfs.py", line 16, in
> from .feature import wfs100, wfs110, wfs200
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/owslib/feature/wfs100.py", line 33, in
> import pyproj
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/pyproj/**init**.py", line 49, in
> import pyproj.network
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> File "/usr/lib/python3.9/site-packages/pyproj/network.py", line 8, in
> import certifi
> File "/usr/lib/python3.9/site-packages/qgis/utils.py", line 799, in _import
> mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'certifi'
> 
> Python version: 3.9.5 (default, May 9 2021, 14:00:28) [GCC 10.2.0]
> QGIS version: 3.18.2-Zürich Zürich, exported
> 
> Python Path:
> /usr/share/qgis/python
> /home/can/.local/share/QGIS/QGIS3/profiles/default/python
> /home/can/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python39.zip
> /usr/lib/python3.9
> /usr/lib/python3.9/lib-dynload
> /home/can/.local/lib/python3.9/site-packages
> /usr/lib/python3.9/site-packages
> /home/can/.local/share/QGIS/QGIS3/profiles/default/python

Thanks. I'll check it out
